### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by ViennaCivicEP2** [ehough/docker-kodi#11]
Hi,

i´ve got a problem with an addon (IPTV) in Kodi.
I get the error "We failed to reach a server. [SSL:CERTIFICATE_VERIFY_FAILED]

Tried looking into the container under /usr/share/kodi/system/certs/'.
Folder 'certs' is missing, so does cacert.pem

Could this be the cause?

I would appreciate your help, as i am fairly new to docker.
How can i add 'cacert.pem' to be persistent?

thanks!

**Comment by ehough** [comment]
Thanks for the report. I'll try to reproduce this locally and come up with a fix. Stand by!

**Comment by ViennaCivicEP2** [comment]
Thanks very much!

**Comment by ehough** [comment]
Are you still experiencing this with the latest version of this image? It should be fixed with the latest versions of this image (Kodi "Leia")

Let us know. Thanks!

**Comment by ehough** [comment]
Closing this issue, but feel free to re-open if necessary.
