### ISSUE TITLE
Guide for lightweight installation?

### ISSUE THREAD

**Issue by AnderssonPeter** [ehough/docker-kodi#13]
Any chance you could add a guide how to install the smallest possible OS that supports this?
Maybe ubuntu mini based?
Exactly what packages do i need to install after base installation?

**Comment by ehough** [comment]
Thanks for your question.

A detailed guide that works for everyone might be difficult as x11docker and Kodi are both somewhat sensitive to the host system's hardware. But I would follow these general steps:

1. Install [Debian `netinst`](https://www.debian.org/distrib/netinst) or [Ubuntu minimal](https://help.ubuntu.com/community/Installation/MinimalCD) on the host. This should leave you with a nice bare-bones Linux installation with (almost) no bloat.
1. Install Docker (Debian instructions [here](https://docs.docker.com/install/linux/docker-ce/debian/), Ubuntu instructions [here](https://docs.docker.com/install/linux/docker-ce/ubuntu/))
1. Install X or Wayland. For many folks this is the trickiest part, but it really boils down to installing the right packages. Debian instructions [here](https://wiki.debian.org/Xorg). For Ubuntu you could try installing [Openbox](https://help.ubuntu.com/community/Openbox) which should bring in the right packages. Be sure to research which package, if any, is required/recommended for your video card.
1. Install [x11docker](https://github.com/mviereck/x11docker) and ensure it works by testing one of the examples given on the README there. e.g. `x11docker --gpu x11docker/xfce glxgears`
1. Proceed with the usage instructions for this image (on the README)

My personal HTPC (where I run Kodi using this image) is pretty slimmed-down, and you can find a list of packages I have installed for it [here](https://pastebin.com/raw/gS9ePkc7). Perhaps that will be useful.

Does that point you in the right direction? Closing this issue but let's continue the discussion!

**Comment by AnderssonPeter** [comment]
Thanks this was exactly what I was looking for, I will try it next week and get back to you with the results!

**Comment by AnderssonPeter** [comment]
I managed to get most of the things working by using debian, but im stuck at the following screen without being able to move the mouse (running in hyper-v while testing)
![image](https://user-images.githubusercontent.com/1308309/49539567-358a2f00-f8ce-11e8-8459-e5ef30496176.png)

**Comment by mviereck** [comment]
You have to move the mouse into the terminal window to get keyboard focus.
Well, if you can't move the mouse, you're stuck.
You can run x11docker with sudo, than you don't need to type in the password here. But that doesn't help you with the mouse.
> running in hyper-v

what does that mean? I thought hyper-v is some sort of Windows virtualization. does this mean you are running Debian in Windows with hyper-v?

**Comment by ehough** [comment]
I agree with @mviereck; try running x11docker with sudo just to get things working. How about: `sudo x11docker --gpu x11docker/xfce glxgears`. Does that work?

If your mouse isn't working, perhaps your virtualization software isn't passing through the USB devices? I've seen that type of screen before and my USB mouse (plugged in to my HTPC) worked.

**Comment by AnderssonPeter** [comment]
hyper-v is a virtualization(just like virtualbox, VMware, Xen and so on platform that comes built in with Windows, but it can run other oses than windows, so running linux works just fine.

Running sudo seems to solve the issue and successfully getting into kodi, but both mouse and keyboard seems to stop working (guessing some hyper-v incompatibly), but I'm happy with the results and I'm going to try this on my htpc!

Thanks for a awesome project!

**Comment by AnderssonPeter** [comment]
Hi again, i have managed to install xorg, docker and x11docker on my physical device.¨

`x11docker --gpu x11docker/xfce glxgears` works a intended, but `x11docker --xorg --vt 7 --pulseaudio --wm none --gpu erichough/kodi` just results in a black screen with a white _ (not flashing) in the upper left corner.

Removing `--vt 7` makes kodi boot up but its super slow when entering the Settings / System menu, its also slow when going to audio so i guess its audio related?

What is `--vt 7` supposed to do?

**Comment by AnderssonPeter** [comment]
using `--alsa` instead of `--pulseaudio` seems to solve the slowdown issue.

**Comment by AnderssonPeter** [comment]
Thanks for your fast response!!
I can't get it to start with `systemd`.
I created the file at `/etc/systemd/system/kodi.system`, replaced ... with my arguments.

running `systemctl start kodi` prompts me for my password then nothing happens, (the x11docker process seems to run in the background, but nothing shows up).

i also enabled the service and restarted, but that had the same result.

What am i missing?

**Comment by ehough** [comment]
Sounds like you're almost there! To confirm, you're able to start things normally *without* using systemd?

[Here's](https://pastebin.com/raw/wgqmh0EP) a copy of the systemd unit file that I've been using for almost a year now. Could you post a copy of yours? Maybe something will jump out.

I would try: `sudo systemctl status kodi` to check the service status. You could also inspect `x11docker`'s logs at `~/.cache/x11docker/x11docker.log` to see if anything interesting shows up there.

**Comment by AnderssonPeter** [comment]
adding `--vt 7` when running as service did the trick!
Thanks for all the support!!!!

Is there any way i could donate some money to this project?

**Comment by ehough** [comment]
Great!

> Is there any way i could donate some money to this project?

Appreciate the gesture, but this project is a hobby and I'm happy to give something back to the community.

I know that the Kodi [accepts donations](https://kodi.tv/contribute/donate) ...
