### ISSUE TITLE
How to add media?

### ISSUE THREAD

**Issue by wsw70** [ehough/docker-kodi#21]
The [documentation ](https://github.com/ehough/docker-kodi#starting-kodi) states that one can use 

    $ x11docker (...) -v /host/path/to/media:/media:ro (...) 

to add media to `docker-kodi` but that results in a failed start: `-v` is a `x11docker` shortcut for verbose output and `/host/path/to/media:/media:ro` is treated as an image name.

**Comment by ehough** [comment]
Hello and thanks for your report.

x11docker interprets anything between a pair of `--` as arguments to the `docker run` command. So if `-v` is getting treated as an argument to x11docker, it sounds like you're missing the `--` pair.

e.g. here is command that will work (split into multiple lines for clarity). Please note the two instances of `--` on the second to last line:

```
/opt/x11docker/x11docker                   \
    --wm=none --xorg                       \
    --gpu --verbose                        \
    -- -v /host/path/to/media:/media:ro -- \
    erichough/kodi
```
Give that a try and let us know?

**Comment by wsw70** [comment]
Ah yes, thank you. That was not the brightest bug submission in my career :)
