### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by wsw70** [ehough/docker-kodi#23]
When starting a fresh container, I get a 100% CPU usage by `kodi-x11 --standalone` (as measured by `htop`.

Kodi is unusable: most of the time it is frozen, then unfreezes for a short amount of time (to freeze back again).

The previous standalone version did not have any problems (Ubuntu 18.04.2, Intel Skylake, 8 GB memory). This is just to highlight the fact that it is likely a misconfiguration on my side (and not a hardware performance limitation)

**Comment by mviereck** [comment]
I wonder if this might be related to https://github.com/ehough/docker-kodi/issues/17 about missing video decoding drivers.
You could try to add `libxv1` and `va-drivers-all` to the image. This probably also fixes https://github.com/ehough/docker-kodi/issues/22.

**Comment by ehough** [comment]
I agree with @mviereck in that this sounds like a driver issue. Could you try installing `libxv1` and `va-drivers-all` into the image to see if that makes any difference? [Here's a `Dockerfile`](https://pastebin.com/raw/5qfbxVki) that you could build and run locally, instead of `erichough/kodi:latest`.

**Comment by wsw70** [comment]
I built the image but the issue is the same (Kodi freezing). The startup is cleaner, though:

```
---> starting Kodi with command: kodi-standalone
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
```

**Comment by wsw70** [comment]
As mentioned in https://github.com/ehough/docker-kodi/issues/17, adding `--priviledged` fixed the issue.

**Comment by wsw70** [comment]
Also, with `--priviledged` the `erichough/kodi:latest` image works great.
