### ISSUE TITLE
Bump Kodi to 18.5

### ISSUE THREAD

**Issue by Greek64** [ehough/docker-kodi#28]
Kodi 18.5 is out for a while.
Also the docker hub image is not updated in the last 5 months and is still in Kodi 18.3.

**Comment by ehough** [comment]
Thanks for the nudge. Working on it now..

**Comment by ehough** [comment]
Fixed in https://github.com/ehough/docker-kodi/commit/dc571a3e9af47d379af6b59e81eaa8b241752f5b and available now on Docker Hub. Please let me know if you have any trouble with the updated image.
