### ISSUE TITLE
add locales

### ISSUE THREAD

**Issue by zixelmike** [ehough/docker-kodi#30]
Not support Russian Language????? =)))))

**Comment by mviereck** [comment]
Try with x11docker option `--lang=ru` (or just `--lang` to get your host system language).
If that does not work, the kodi Dockerfile might need additional packages, at least package `locales`.

**Comment by zixelmike** [comment]
x11docker note: Option --lang: Generation of locale ru_RU.utf8 failed. =((

**Comment by mviereck** [comment]
> Generation of locale ru_RU.utf8 failed.

You could try to add package locales. A new Dockerfile could be:
```
FROM erichough/kodi
RUN apt-get update && apt-get install -y locales
```
Build a new image with this Dockerfile and try it with `--lang=ru`.

**Comment by mviereck** [comment]
Another way: This should provide a translated kodi: https://kodi.wiki/view/Add-on:Russian

**Comment by zixelmike** [comment]
> Another way: This should provide a translated kodi: https://kodi.wiki/view/Add-on:Russian

Don`t have language addons in Kodi....

**Comment by zixelmike** [comment]
> > Generation of locale ru_RU.utf8 failed.
> 
> You could try to add package `locales`. A new Dockerfile could be:
> 
> ```
> FROM erichough/kodi
> RUN apt-get update && apt-get install -y locales
> ```
> 
> Build a new image with this Dockerfile and try it with `--lang=ru`.

It working, ThankYou! =)

**Comment by mviereck** [comment]
> It working, ThankYou! =)

Great!
@ehough Would you consider to add `locales` to your Dockerfile? It should add only a few kb.

**Comment by zixelmike** [comment]
Yes, it`s working

**Comment by ehough** [comment]
> @ehough Would you consider to add locales to your Dockerfile? It should add only a few kb to the image

Sure thing. Thank you both very much for figuring this out. And special thanks to @mviereck for continuing to be a rock star problem solver!
