### ISSUE TITLE
[Discussion] Ideas / Improvements / In-Use

### ISSUE THREAD

**Issue by gsantner** [ehough/docker-kodi#34]
Hello, thanks for this project. I'm using since a while now and pretty happy with it.

I thought to open a issue for discussion and sharing ideas to improve the project.  
Myself having some dockerfile changes (and custom docker image), that I wanted to share, maybe the one or other might sense to be picked up by the project by default.

**Comment by gsantner** [comment]
My overall changes to Dockerfile:


![grafik](https://user-images.githubusercontent.com/6735650/85542512-71ecbf80-b619-11ea-901f-ec2790e0af65.png)


@ehough 
What do you think about making these changes on master?:

- Use `DEBIAN_FRONTEND=noninteractive` before apt calls, and export it as env var. I have run into cases where docker build would hang/freeze and waiting for input at apt.
- Add apt pkg `libnss3`, required for DRM TV Addons to work.
- Add apt pkg `curl`, helpful for health checks and some addons might use some executables that use normal-non-python curl.
- For me, alsa-utils where rerquired for audio to work properly, not sure if it makes it work for others as well


Note, when `libnss3` is not installed:

![kodi-screenshot](https://user-images.githubusercontent.com/6735650/85542771-b4ae9780-b619-11ea-93da-7eaac55c54f6.png)

**Comment by ehough** [comment]
Thanks so much for these great suggestions! And sorry for my late response.

> Use DEBIAN_FRONTEND=noninteractive before apt calls, and export it as env var. I have run into cases where docker build would hang/freeze and waiting for input at apt.

Good idea. I'll add it as an `ARG` instead of `ENV`. See [here](https://github.com/ehough/docker-nfs-server/pull/3#issuecomment-387880692) for the rationale.

> Add apt pkg libnss3, required for DRM TV Addons to work.

I'll be merging that PR (I promise!) as soon as I'm able to run some local testing. Did you also have to install `libnss3-tools`? Or just `libnss3`?

> Add apt pkg curl, helpful for health checks and some addons might use some executables that use normal-non-python curl.

Any chance you have some examples of add-ons that invoke the `curl` binary? I know it's a fairly standard-issue tool to have installed, but I want to make sure that any package added to the base image has a compelling reason to be there.

> For me, alsa-utils where rerquired for audio to work properly, not sure if it makes it work for others as well

Interesting. You don't remember what error message or behavior you saw, by chance? I'll investigate adding that package.

Last note for now: if you haven't considered it already, you could just extend this image to make your custom mods. e.g.

```Dockerfile
FROM erichough/kodi

RUN dpkg --add-architecture i386 && \
    sed -i ...
   ...
```
Know what I mean?

That way you wouldn't have to update your image every time I update the base image.

**Comment by gsantner** [comment]
> Thanks so much for these great suggestions! And sorry for my late response.
> 
> > Use DEBIAN_FRONTEND=noninteractive before apt calls, and export it as env var. I have run into cases where docker build would hang/freeze and waiting for input at apt.
> 
> Good idea. I'll add it as an `ARG` instead of `ENV`. See [here](https://github.com/ehough/docker-nfs-server/pull/3#issuecomment-387880692) for the rationale.

don't really care here

> 
> > Add apt pkg libnss3, required for DRM TV Addons to work.
> 
> I'll be merging that PR (I promise!) as soon as I'm able to run some local testing. Did you also have to install `libnss3-tools`? Or just `libnss3`?
> 

I don't have tools.

> > Add apt pkg curl, helpful for health checks and some addons might use some executables that use normal-non-python curl.
> 
> Any chance you have some examples of add-ons that invoke the `curl` binary? I know it's a fairly standard-issue tool to have installed, but I want to make sure that any package added to the base image has a compelling reason to be there.

Often things don't work, and then you can bash into docker container. And if not even basics are there it's troublesome to debug why EPG streams.xml doesn't download.

> 
> > For me, alsa-utils where rerquired for audio to work properly, not sure if it makes it work for others as well
> 
> Interesting. You don't remember what error message or behavior you saw, by chance? I'll investigate adding that package.

No error message. Just nothing with audio or any audio output channel was working for me.

> 
> Last note for now: if you haven't considered it already, you could just extend this image to make your custom mods. e.g.
> 
> ```dockerfile
> FROM erichough/kodi
> 
> RUN dpkg --add-architecture i386 && \
>     sed -i ...
>    ...
> ```
> 
> Know what I mean?
> 
> That way you wouldn't have to update your image every time I update the base image.

Yeah but I found it easier to maintain forked Dockerfile for myself. For the reason, I can independently update/downgrade Kodi version if new update is out..or something doesn't work.

**Comment by gsantner** [comment]
Closing. Don't use Kodi in Docker anymore. It's been 4 years and there are better options now (Flatpak/Snap) with similar goal...even supported by the Kodi project itself.
